name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        jdkversion: [17]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdkversion }}
          cache: "maven"

      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Remove
        run: rm target/* -f
      - name: Build with Maven
        run: mvn -V -B clean package --file pom.xml
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: MMOItems
          path: core/target
      - name: Set Short SHA
        id: short-sha
        run: echo "SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Generate release tag
        id: tag
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: automatic releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "zh-hans-${{ env.SHORT_SHA }}"
          prerelease: false
          title: "MMOItems-${{ env.SHORT_SHA }} ${{ env.version }}-Hans Auto Build"
          files: |
            target/*.jar
